### ISSUE TITLE
gkd.json5 和  gkd.version.json5 的问题

### ISSUE THREAD

**Issue by aoguai** [gkd-kit/tools#1]
希望可以允许 stdoutGkdVersion 和 updatePkgVersion 函数传参
否则使用规则公共模板中 build_release.yml 时`node -e "import('@gkd-kit/tools').then((m) => m.stdoutGkdVersion());"` 只能固定访问`./dist/gkd.version.json5`文件

**Comment by aoguai** [comment]
目前发现还有 updateDist 也写死了 gkd.json5 和  gkd.version.json5

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription-template/commit/3c2c302692e3f5b1f85738435ca7af72c8125807
